apiVersion: v1
kind: ConfigMap
metadata:
  name: goldpinger-manifest
  namespace: default
data:
  goldpinger.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: goldpinger
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: goldpinger
    rules:
    - apiGroups: [""]
      resources: ["pods", "nodes"]
      verbs: ["get", "list", "watch"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: goldpinger
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: goldpinger
    subjects:
    - kind: ServiceAccount
      name: goldpinger
      namespace: kube-system
    ---
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: goldpinger
      namespace: kube-system
      labels:
        app: goldpinger
    spec:
      selector:
        matchLabels:
          app: goldpinger
      template:
        metadata:
          labels:
            app: goldpinger
        spec:
          serviceAccountName: goldpinger
          containers:
          - name: goldpinger
            image: bloomberg/goldpinger:3.10.0
            args:
            - --host=0.0.0.0
            - --port=8080
            env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            ports:
            - containerPort: 8080
              name: http
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: install-goldpinger
spec:
  clusterSelector: 
    matchLabels:
      app: goldpinger
  syncMode: Continuous
  policyRefs:
    - name: goldpinger-manifest
      namespace: default
      kind: ConfigMap
